import type { Asset } from './types'

// TODO(api): replace with TanStack Query against the C# backend
// (GET /api/assets, GET /api/assets/:id with lifecycle events). The shape
// below should mirror what the API returns.

export const MOCK_ASSETS: Asset[] = [
  {
    id: '1',
    assetTag: 'FL-LT-0001',
    name: 'MacBook Pro 16" M4',
    category: 'laptop',
    lifecycleState: 'in_use',
    ownership: 'owned',
    serialNumber: 'C02XK1ABCDEF',
    location: 'Copenhagen HQ',
    requestedAt: '2025-08-20',
    orderedAt: '2025-08-22',
    receivedAt: '2025-09-10',
    deployedAt: '2025-09-12',
    currentAssignment: {
      id: 'a1-cur',
      assigneeName: 'Anna Sørensen',
      assigneeEmail: 'anna@firstlineit.dk',
      location: 'Copenhagen HQ',
      assignedAt: '2025-09-12',
    },
    assignments: [
      {
        id: 'a1-cur',
        assigneeName: 'Anna Sørensen',
        assigneeEmail: 'anna@firstlineit.dk',
        location: 'Copenhagen HQ',
        assignedAt: '2025-09-12',
      },
    ],
    purchase: {
      vendor: 'Humac Business',
      purchaseOrder: 'PO-2025-0421',
      purchaseDate: '2025-09-10',
      price: { amount: 32500, currency: 'DKK' },
    },
    depreciation: {
      method: 'straight_line',
      usefulLifeMonths: 36,
      residualValue: { amount: 3000, currency: 'DKK' },
    },
    warranties: [
      {
        id: 'w1-a',
        kind: 'manufacturer',
        provider: 'Apple',
        startsAt: '2025-09-10',
        endsAt: '2026-09-10',
      },
      {
        id: 'w1-b',
        kind: 'extended',
        provider: 'AppleCare+ for Business',
        reference: 'AC-99831',
        startsAt: '2025-09-10',
        endsAt: '2028-09-10',
        coverageNotes: 'Includes accidental damage, 2 incidents/year',
      },
    ],
    events: [
      {
        id: 'e1-1',
        occurredAt: '2025-08-20T09:00:00Z',
        actor: 'Mads Holm',
        kind: 'state_changed',
        payload: { from: 'requested', to: 'requested' },
        notes: 'Request submitted by Anna Sørensen',
      },
      {
        id: 'e1-2',
        occurredAt: '2025-08-22T14:00:00Z',
        actor: 'Procurement',
        kind: 'state_changed',
        payload: { from: 'requested', to: 'ordered', po: 'PO-2025-0421' },
      },
      {
        id: 'e1-3',
        occurredAt: '2025-09-10T11:30:00Z',
        actor: 'IT Reception',
        kind: 'state_changed',
        payload: { from: 'ordered', to: 'in_stock' },
        notes: 'Received from Humac, serial verified',
      },
      {
        id: 'e1-4',
        occurredAt: '2025-09-12T08:15:00Z',
        actor: 'IT Support',
        kind: 'assigned',
        payload: { assignee: 'Anna Sørensen' },
      },
      {
        id: 'e1-5',
        occurredAt: '2025-09-12T08:20:00Z',
        actor: 'IT Support',
        kind: 'state_changed',
        payload: { from: 'in_stock', to: 'in_use' },
      },
    ],
  },
  {
    id: '2',
    assetTag: 'FL-LT-0002',
    name: 'ThinkPad X1 Carbon Gen 12',
    category: 'laptop',
    lifecycleState: 'in_maintenance',
    ownership: 'owned',
    serialNumber: 'PF3K1XYZ',
    location: 'Aarhus Office',
    orderedAt: '2024-10-28',
    receivedAt: '2024-11-02',
    deployedAt: '2024-11-03',
    currentAssignment: {
      id: 'a2-cur',
      assigneeName: 'Mikkel Holm',
      assigneeEmail: 'mikkel@firstlineit.dk',
      location: 'Aarhus Office',
      assignedAt: '2024-11-03',
    },
    assignments: [
      {
        id: 'a2-cur',
        assigneeName: 'Mikkel Holm',
        assigneeEmail: 'mikkel@firstlineit.dk',
        location: 'Aarhus Office',
        assignedAt: '2024-11-03',
      },
    ],
    purchase: {
      vendor: 'Atea',
      purchaseOrder: 'PO-2024-1187',
      purchaseDate: '2024-11-02',
      price: { amount: 18900, currency: 'DKK' },
    },
    depreciation: {
      method: 'straight_line',
      usefulLifeMonths: 36,
      residualValue: { amount: 1500, currency: 'DKK' },
    },
    warranties: [
      {
        id: 'w2-a',
        kind: 'manufacturer',
        provider: 'Lenovo',
        startsAt: '2024-11-02',
        endsAt: '2027-11-02',
      },
      {
        id: 'w2-b',
        kind: 'service_contract',
        provider: 'Atea Premier Support',
        reference: 'SC-44219',
        startsAt: '2024-11-02',
        endsAt: '2027-11-02',
        coverageNotes: 'Next-business-day on-site',
      },
    ],
    events: [
      {
        id: 'e2-1',
        occurredAt: '2024-11-02T10:00:00Z',
        actor: 'IT Reception',
        kind: 'state_changed',
        payload: { from: 'ordered', to: 'in_stock' },
      },
      {
        id: 'e2-2',
        occurredAt: '2024-11-03T09:00:00Z',
        actor: 'IT Support',
        kind: 'assigned',
        payload: { assignee: 'Mikkel Holm' },
      },
      {
        id: 'e2-3',
        occurredAt: '2024-11-03T09:05:00Z',
        actor: 'IT Support',
        kind: 'state_changed',
        payload: { from: 'in_stock', to: 'in_use' },
      },
      {
        id: 'e2-4',
        occurredAt: '2026-05-18T13:42:00Z',
        actor: 'Mikkel Holm',
        kind: 'note',
        notes: 'Keyboard backlight intermittent, raising ticket',
      },
      {
        id: 'e2-5',
        occurredAt: '2026-05-20T08:00:00Z',
        actor: 'IT Support',
        kind: 'maintenance_started',
        payload: { ticket: 'INC-7711', vendor: 'Atea' },
      },
      {
        id: 'e2-6',
        occurredAt: '2026-05-20T08:05:00Z',
        actor: 'IT Support',
        kind: 'state_changed',
        payload: { from: 'in_use', to: 'in_maintenance' },
      },
    ],
  },
  {
    id: '3',
    assetTag: 'FL-MN-0014',
    name: 'Dell UltraSharp U2723QE',
    category: 'monitor',
    lifecycleState: 'in_stock',
    ownership: 'owned',
    serialNumber: 'CN-0H3M2',
    location: 'Copenhagen HQ — Storage',
    orderedAt: '2025-02-15',
    receivedAt: '2025-02-20',
    assignments: [],
    purchase: {
      vendor: 'Dell Technologies',
      purchaseOrder: 'PO-2025-0099',
      purchaseDate: '2025-02-20',
      price: { amount: 4200, currency: 'DKK' },
    },
    depreciation: {
      method: 'straight_line',
      usefulLifeMonths: 60,
      residualValue: { amount: 0, currency: 'DKK' },
    },
    warranties: [
      {
        id: 'w3-a',
        kind: 'manufacturer',
        provider: 'Dell',
        startsAt: '2025-02-20',
        endsAt: '2028-02-20',
        coverageNotes: 'Premium Panel Exchange',
      },
    ],
    events: [
      {
        id: 'e3-1',
        occurredAt: '2025-02-20T10:00:00Z',
        actor: 'IT Reception',
        kind: 'state_changed',
        payload: { from: 'ordered', to: 'in_stock' },
      },
    ],
  },
  {
    id: '4',
    assetTag: 'FL-PH-0033',
    name: 'iPhone 17 Pro',
    category: 'phone',
    lifecycleState: 'leased_in',
    ownership: 'leased_in',
    serialNumber: 'F2LXK99QR',
    location: 'Remote — DK',
    receivedAt: '2025-10-01',
    deployedAt: '2025-10-01',
    currentAssignment: {
      id: 'a4-cur',
      assigneeName: 'Sofia Lind',
      assigneeEmail: 'sofia@firstlineit.dk',
      location: 'Remote — DK',
      assignedAt: '2025-10-01',
    },
    assignments: [
      {
        id: 'a4-cur',
        assigneeName: 'Sofia Lind',
        assigneeEmail: 'sofia@firstlineit.dk',
        location: 'Remote — DK',
        assignedAt: '2025-10-01',
      },
    ],
    purchase: {
      vendor: '3 Erhverv',
      purchaseDate: '2025-10-01',
      price: { amount: 0, currency: 'DKK' },
    },
    lease: {
      vendor: '3 Erhverv',
      contractRef: 'LEASE-3-2025-882',
      startsAt: '2025-10-01',
      endsAt: '2027-10-01',
      monthlyCost: { amount: 449, currency: 'DKK' },
    },
    warranties: [
      {
        id: 'w4-a',
        kind: 'manufacturer',
        provider: 'Apple',
        startsAt: '2025-10-01',
        endsAt: '2026-10-01',
      },
    ],
    events: [
      {
        id: 'e4-1',
        occurredAt: '2025-10-01T09:00:00Z',
        actor: 'IT Support',
        kind: 'lease_started',
        payload: { vendor: '3 Erhverv', contract: 'LEASE-3-2025-882' },
      },
      {
        id: 'e4-2',
        occurredAt: '2025-10-01T09:15:00Z',
        actor: 'IT Support',
        kind: 'assigned',
        payload: { assignee: 'Sofia Lind' },
      },
      {
        id: 'e4-3',
        occurredAt: '2025-10-01T09:20:00Z',
        actor: 'IT Support',
        kind: 'state_changed',
        payload: { from: 'in_stock', to: 'leased_in' },
      },
    ],
  },
  {
    id: '5',
    assetTag: 'FL-SV-0002',
    name: 'Dell PowerEdge R660',
    category: 'server',
    lifecycleState: 'in_maintenance',
    ownership: 'owned',
    serialNumber: 'SVR-2024-002',
    location: 'Copenhagen DC Rack 4',
    orderedAt: '2024-03-30',
    receivedAt: '2024-04-12',
    deployedAt: '2024-04-15',
    assignments: [],
    purchase: {
      vendor: 'Dell Technologies',
      purchaseOrder: 'PO-2024-0301',
      purchaseDate: '2024-04-12',
      price: { amount: 142000, currency: 'DKK' },
    },
    depreciation: {
      method: 'declining_balance',
      usefulLifeMonths: 60,
      residualValue: { amount: 10000, currency: 'DKK' },
    },
    warranties: [
      {
        id: 'w5-a',
        kind: 'manufacturer',
        provider: 'Dell ProSupport Plus',
        reference: 'PSP-559912',
        startsAt: '2024-04-12',
        endsAt: '2029-04-12',
        coverageNotes: '4hr mission-critical, on-site',
      },
    ],
    events: [
      {
        id: 'e5-1',
        occurredAt: '2024-04-15T10:00:00Z',
        actor: 'Infra Team',
        kind: 'state_changed',
        payload: { from: 'in_stock', to: 'in_use' },
      },
      {
        id: 'e5-2',
        occurredAt: '2026-05-22T02:11:00Z',
        actor: 'Monitoring',
        kind: 'note',
        notes: 'Disk 4 predictive failure SMART warning',
      },
      {
        id: 'e5-3',
        occurredAt: '2026-05-22T09:00:00Z',
        actor: 'Infra Team',
        kind: 'maintenance_started',
        payload: { ticket: 'CHG-2206', vendor: 'Dell ProSupport' },
      },
      {
        id: 'e5-4',
        occurredAt: '2026-05-22T09:05:00Z',
        actor: 'Infra Team',
        kind: 'state_changed',
        payload: { from: 'in_use', to: 'in_maintenance' },
      },
    ],
  },
  {
    id: '6',
    assetTag: 'FL-LT-0008',
    name: 'MacBook Air 13" M3',
    category: 'laptop',
    lifecycleState: 'disposed',
    ownership: 'owned',
    serialNumber: 'C02OLD2022',
    location: 'Disposed',
    orderedAt: '2022-05-10',
    receivedAt: '2022-05-18',
    deployedAt: '2022-05-20',
    retiredAt: '2025-12-01',
    disposedAt: '2026-01-15',
    assignments: [
      {
        id: 'a6-1',
        assigneeName: 'Jonas Pedersen',
        assigneeEmail: 'jonas@firstlineit.dk',
        location: 'Copenhagen HQ',
        assignedAt: '2022-05-20',
        returnedAt: '2024-03-10',
        notes: 'Returned at offboarding',
      },
      {
        id: 'a6-2',
        assigneeName: 'Sara Bach',
        assigneeEmail: 'sara@firstlineit.dk',
        location: 'Aarhus Office',
        assignedAt: '2024-03-15',
        returnedAt: '2025-11-20',
        notes: 'Returned for refresh cycle',
      },
    ],
    purchase: {
      vendor: 'Humac Business',
      purchaseOrder: 'PO-2022-0188',
      purchaseDate: '2022-05-18',
      price: { amount: 13500, currency: 'DKK' },
    },
    depreciation: {
      method: 'straight_line',
      usefulLifeMonths: 36,
      residualValue: { amount: 1000, currency: 'DKK' },
    },
    warranties: [
      {
        id: 'w6-a',
        kind: 'manufacturer',
        provider: 'Apple',
        startsAt: '2022-05-18',
        endsAt: '2023-05-18',
      },
    ],
    disposal: {
      method: 'recycled',
      disposedAt: '2026-01-15',
      disposedBy: 'IT Support',
      recipient: 'Refurb Aps',
      certificateRef: 'WEEE-2026-0014',
      notes: 'WEEE compliant disposal, data sanitized per NIST 800-88',
    },
    events: [
      {
        id: 'e6-1',
        occurredAt: '2022-05-20T10:00:00Z',
        actor: 'IT Support',
        kind: 'assigned',
        payload: { assignee: 'Jonas Pedersen' },
      },
      {
        id: 'e6-2',
        occurredAt: '2024-03-10T15:00:00Z',
        actor: 'IT Support',
        kind: 'unassigned',
        payload: { from: 'Jonas Pedersen' },
        notes: 'Offboarding',
      },
      {
        id: 'e6-3',
        occurredAt: '2024-03-15T09:00:00Z',
        actor: 'IT Support',
        kind: 'assigned',
        payload: { assignee: 'Sara Bach' },
      },
      {
        id: 'e6-4',
        occurredAt: '2025-11-20T11:00:00Z',
        actor: 'IT Support',
        kind: 'unassigned',
        payload: { from: 'Sara Bach' },
      },
      {
        id: 'e6-5',
        occurredAt: '2025-12-01T10:00:00Z',
        actor: 'IT Support',
        kind: 'state_changed',
        payload: { from: 'in_stock', to: 'retired' },
        notes: 'End of useful life, replaced with M4 model',
      },
      {
        id: 'e6-6',
        occurredAt: '2026-01-15T13:00:00Z',
        actor: 'IT Support',
        kind: 'disposed',
        payload: {
          method: 'recycled',
          recipient: 'Refurb Aps',
          certificate: 'WEEE-2026-0014',
        },
      },
    ],
  },
]
