import type { Asset } from './types'

// TODO(api): replace with TanStack Query hook against the C# backend
// (e.g. GET /api/assets). This mock exists only so the shell renders
// something meaningful before the API is wired up.
export const MOCK_ASSETS: Asset[] = [
  {
    id: '1',
    assetTag: 'FL-LT-0001',
    name: 'MacBook Pro 16" M4',
    category: 'laptop',
    status: 'in_use',
    serialNumber: 'C02XK1ABCDEF',
    assignedTo: 'Anna Sørensen',
    location: 'Copenhagen HQ',
    purchaseDate: '2025-09-12',
    warrantyEndsAt: '2028-09-12',
  },
  {
    id: '2',
    assetTag: 'FL-LT-0002',
    name: 'ThinkPad X1 Carbon Gen 12',
    category: 'laptop',
    status: 'in_use',
    serialNumber: 'PF3K1XYZ',
    assignedTo: 'Mikkel Holm',
    location: 'Aarhus Office',
    purchaseDate: '2024-11-03',
    warrantyEndsAt: '2027-11-03',
  },
  {
    id: '3',
    assetTag: 'FL-MN-0014',
    name: 'Dell UltraSharp U2723QE',
    category: 'monitor',
    status: 'in_stock',
    serialNumber: 'CN-0H3M2',
    assignedTo: null,
    location: 'Copenhagen HQ — Storage',
    purchaseDate: '2025-02-20',
    warrantyEndsAt: '2028-02-20',
  },
  {
    id: '4',
    assetTag: 'FL-PH-0033',
    name: 'iPhone 17 Pro',
    category: 'phone',
    status: 'in_use',
    serialNumber: 'F2LXK99QR',
    assignedTo: 'Sofia Lind',
    location: 'Remote — DK',
    purchaseDate: '2025-10-01',
    warrantyEndsAt: '2026-10-01',
  },
  {
    id: '5',
    assetTag: 'FL-SV-0002',
    name: 'Dell PowerEdge R660',
    category: 'server',
    status: 'maintenance',
    serialNumber: 'SVR-2024-002',
    assignedTo: null,
    location: 'Copenhagen DC Rack 4',
    purchaseDate: '2024-04-15',
    warrantyEndsAt: '2029-04-15',
  },
  {
    id: '6',
    assetTag: 'FL-LT-0008',
    name: 'MacBook Air 13" M3',
    category: 'laptop',
    status: 'retired',
    serialNumber: 'C02OLD2022',
    assignedTo: null,
    location: 'Disposed',
    purchaseDate: '2022-05-20',
    warrantyEndsAt: '2025-05-20',
  },
]
