import type { MaintenanceTicket } from './types'

export const MOCK_TICKETS: MaintenanceTicket[] = [
  {
    id: 't-1',
    title: 'Kølerblæser larmer kraftigt',
    assetId: '2',
    assetName: 'ThinkPad X1 Carbon Gen 12',
    status: 'in_progress',
    priority: 'high',
    description:
      'Brugeren rapporterer høj larm fra blæseren. Mistanke om støv eller defekt blæser.',
    reportedBy: 'Mikkel Holm',
    assignedTo: 'IT Support',
    vendor: 'Atea Premier Support',
    ticketRef: 'INC-2026-0042',
    createdAt: '2026-05-20T08:30:00Z',
    scheduledFor: '2026-05-28',
  },
  {
    id: 't-2',
    title: 'Skærmen flimrer',
    assetId: '4',
    assetName: 'iPhone 17 Pro',
    status: 'open',
    priority: 'normal',
    description: 'Skærmen flimrer ved lav lysstyrke.',
    reportedBy: 'Sofia Lind',
    createdAt: '2026-05-24T14:10:00Z',
  },
  {
    id: 't-3',
    title: 'Firmware-opdatering på server',
    assetId: '5',
    assetName: 'Dell PowerEdge R660',
    status: 'awaiting_parts',
    priority: 'low',
    description:
      'Planlagt firmware-upgrade i forbindelse med kvartalsvis vedligehold.',
    reportedBy: 'Infra Team',
    assignedTo: 'Infra Team',
    createdAt: '2026-05-18T09:00:00Z',
    scheduledFor: '2026-06-01',
  },
  {
    id: 't-4',
    title: 'Tastaturet reagerer ikke',
    assetId: '1',
    assetName: 'MacBook Pro 16" M4',
    status: 'resolved',
    priority: 'high',
    description: 'Flere taster reagerer ikke. AppleCare-reparation.',
    reportedBy: 'Anna Sørensen',
    assignedTo: 'IT Support',
    vendor: 'Humac Service Center',
    ticketRef: 'AC-2026-0019',
    createdAt: '2026-05-02T11:00:00Z',
    resolvedAt: '2026-05-10',
    resolutionNotes: 'Tastatur udskiftet under garanti.',
  },
]
