import type { License } from './types'

export const MOCK_LICENSES: License[] = [
  {
    id: 'lic-1',
    name: 'Microsoft 365 Business Standard',
    vendor: 'Microsoft',
    kind: 'subscription',
    seatsTotal: 50,
    seatsUsed: 42,
    costPerSeatPerYear: 1380,
    currency: 'DKK',
    owner: 'IT Admin',
    acquiredAt: '2024-08-01',
    renewsAt: '2026-08-01',
  },
  {
    id: 'lic-2',
    name: 'Adobe Creative Cloud All Apps',
    vendor: 'Adobe',
    kind: 'subscription',
    seatsTotal: 8,
    seatsUsed: 6,
    costPerSeatPerYear: 9600,
    currency: 'DKK',
    owner: 'Marketing',
    acquiredAt: '2025-04-15',
    renewsAt: '2026-04-15',
  },
  {
    id: 'lic-3',
    name: 'Atlassian Jira Cloud',
    vendor: 'Atlassian',
    kind: 'cloud',
    seatsTotal: 30,
    seatsUsed: 25,
    costPerSeatPerYear: 720,
    currency: 'DKK',
    owner: 'Engineering',
    acquiredAt: '2024-11-10',
    renewsAt: '2026-11-10',
  },
  {
    id: 'lic-4',
    name: 'Slack Pro',
    vendor: 'Slack Technologies',
    kind: 'subscription',
    seatsTotal: 60,
    seatsUsed: 55,
    costPerSeatPerYear: 540,
    currency: 'DKK',
    owner: 'IT Admin',
    acquiredAt: '2024-02-01',
    renewsAt: '2026-06-30',
  },
  {
    id: 'lic-5',
    name: 'Figma Professional',
    vendor: 'Figma',
    kind: 'cloud',
    seatsTotal: 12,
    seatsUsed: 9,
    costPerSeatPerYear: 1080,
    currency: 'DKK',
    owner: 'Design',
    acquiredAt: '2025-01-15',
    renewsAt: '2026-01-15',
  },
]
