import type { License } from './types'

export const MOCK_LICENSES: License[] = [
  {
    id: 'lic-1',
    name: 'Microsoft 365 Business Standard',
    vendor: 'Microsoft',
    kind: 'subscription',
    serviceType: 'license',
    billingModel: 'per_seat',
    seatsTotal: 50,
    seatsUsed: 42,
    costPerSeatPerYear: 1380,
    currency: 'DKK',
    owner: 'IT Admin',
    acquiredAt: '2024-08-01',
    renewsAt: '2026-08-01',
  },
  {
    id: 'lic-2',
    name: 'Adobe Creative Cloud All Apps',
    vendor: 'Adobe',
    kind: 'subscription',
    serviceType: 'license',
    billingModel: 'per_seat',
    seatsTotal: 8,
    seatsUsed: 9,
    costPerSeatPerYear: 9600,
    currency: 'DKK',
    owner: 'Marketing',
    acquiredAt: '2025-04-15',
    renewsAt: '2026-04-15',
    notes: 'Over-deployeret — 1 plads for meget.',
  },
  {
    id: 'lic-3',
    name: 'Atlassian Jira Cloud',
    vendor: 'Atlassian',
    kind: 'cloud',
    serviceType: 'license',
    billingModel: 'per_seat',
    seatsTotal: 30,
    seatsUsed: 25,
    costPerSeatPerYear: 720,
    currency: 'DKK',
    owner: 'Engineering',
    acquiredAt: '2024-11-10',
    renewsAt: '2026-11-10',
  },
  {
    id: 'lic-4',
    name: 'Slack Pro',
    vendor: 'Slack Technologies',
    kind: 'subscription',
    serviceType: 'license',
    billingModel: 'per_seat',
    seatsTotal: 60,
    seatsUsed: 55,
    costPerSeatPerYear: 540,
    currency: 'DKK',
    owner: 'IT Admin',
    acquiredAt: '2024-02-01',
    renewsAt: '2026-06-30',
  },
  {
    id: 'lic-5',
    name: 'Figma Professional',
    vendor: 'Figma',
    kind: 'cloud',
    serviceType: 'license',
    billingModel: 'per_seat',
    seatsTotal: 12,
    seatsUsed: 9,
    costPerSeatPerYear: 1080,
    currency: 'DKK',
    owner: 'Design',
    acquiredAt: '2025-01-15',
    renewsAt: '2026-01-15',
  },
  // ── Cloud services (flat monthly billing, no seat model) ──────────────
  {
    id: 'cloud-1',
    name: 'Microsoft Azure (Pay-as-you-go)',
    vendor: 'Microsoft',
    kind: 'cloud',
    serviceType: 'cloud_service',
    billingModel: 'flat_monthly',
    monthlyCost: 18500,
    seatsTotal: 0,
    seatsUsed: 0,
    currency: 'DKK',
    owner: 'Infra Team',
    acquiredAt: '2024-03-01',
  },
  {
    id: 'cloud-2',
    name: 'Amazon Web Services',
    vendor: 'AWS',
    kind: 'cloud',
    serviceType: 'cloud_service',
    billingModel: 'flat_monthly',
    monthlyCost: 9200,
    seatsTotal: 0,
    seatsUsed: 0,
    currency: 'DKK',
    owner: 'Engineering',
    acquiredAt: '2025-02-01',
  },
  {
    id: 'cloud-3',
    name: 'Cloudflare Pro',
    vendor: 'Cloudflare',
    kind: 'cloud',
    serviceType: 'cloud_service',
    billingModel: 'flat_monthly',
    monthlyCost: 1500,
    seatsTotal: 0,
    seatsUsed: 0,
    currency: 'DKK',
    owner: 'Infra Team',
    acquiredAt: '2025-06-01',
    renewsAt: '2026-06-01',
  },
]
